#! /bin/bash

function readlink_f() {
  local src='import os,sys;print(os.path.realpath(sys.argv[1]))'
  python3 -c "${src}" "$1" || python -c "${src}" "$1"
}

ROOT_DIR="$(cd "$(dirname "$(readlink_f "$0")")" && cd .. && pwd)"
cd "${ROOT_DIR}" || exit 1

set -eu
set -o pipefail

mkdir -p "./dev-var/postgres"

export "USER_ID=$(id -u)"
export "GROUP_ID=$(id -g)"

docker-compose -f docker-compose.dev.yml run \
  --rm \
  --user "$(id -u)" \
  --use-aliases \
  -e 'PGPASSWORD=the-gear-of-seasons' \
  postgres-dev \
  psql  '--username=the-gear-of-seasons' \
        '--host=postgres-dev' \
        "$@" \
        'the-gear-of-seasons'
