#! /bin/bash

function readlink_f() {
  local src='import os,sys;print(os.path.realpath(sys.argv[1]))'
  python3 -c "${src}" "$1" || python -c "${src}" "$1"
}

ROOT_DIR="$(cd "$(dirname "$(readlink_f "$0")")" && cd .. && pwd)"
cd "${ROOT_DIR}" || exit 1

set -eu
set -o pipefail

dev/down
dev/clean
dev/up
dev/migrate
