[package]
name = "restore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "std", "env-filter", "chrono" ] }
clap = "4.5.28"
md5 = "0.7.0"
walkdir = "2.5.0"
image = "0.24.9" # imagehash requires this ver.
imagehash = "0.3.0"
