name: 'Run all unit tests'

on:
  push:
    branches: [magistra]
  pull_request:
    branches: [magistra]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Print env
        run: uname -a

      # https://github.com/actions/checkout
      - name: Setup repo
        uses: actions/checkout@v4.2.2

      # https://github.com/FedericoCarboni/setup-ffmpeg
      - uses: FedericoCarboni/setup-ffmpeg@v3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      # https://github.com/actions/setup-node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup ImageMagick (mac OS)
        run: |
          # You need brew on mac OS
          brew install imagemagick
        if: matrix.os == 'macOS-latest'

      - name: Setup ImageMagick (Ubuntu)
        run: |
          sudo curl --output "/usr/bin/magick" "https://imagemagick.org/archive/binaries/magick"
          sudo chmod a+x "/usr/bin/magick"
          sudo apt-get install --no-install-recommends libfuse2
          magick --version
        if: matrix.os == 'ubuntu-latest'

      - name: Prepare
        run: dev/install

      - name: Run tests
        run: dev/test
